### PR TITLE
[CMSIS Core] Added CM55 Power Mode Control Registers definition

### PR DESCRIPTION
**Pull request by FabKlein**
CM55 Power Mode Control Registers structure definition added

### CODE REVIEW

**Comment by JonatanAntoni** [comment]
Thanks @FabKlein, Please update the file version (e.g. increment to 1.2.0 as this is a minor functional update) and date in the header.

**Review by GuentherMartin — APPROVED** [review]
Looks correct to me.

**Comment by JonatanAntoni** [comment]
Can one of the admins verify this patch?

**Comment by JonatanAntoni** [comment]
ok to test

**Pull request merged**
