### PR TITLE
CMSIS-DAP: Add Error LED to DAP_HostStatus.

### PR DESCRIPTION
**Pull request by zyp**

### CODE REVIEW

**Comment by grasci-arm** [comment]
Can one of the admins verify this patch?

**Comment by JonatanAntoni** [comment]
@RobertRostohar, is this a fair addition to the docs?

**Review by RobertRostohar — COMMENTED** [review]
There is no Error status LED supported in CMSIS-DAP. Status LEDs exist only to indicate "Connected" and "Target Running".

**Comment by zyp** [comment]
This is a proposal to add an Error status LED.

**Comment by JonatanAntoni** [comment]
@zyp,

Well, this is a pull-request to change the actual documentation.
If you want to raise a feature request you can either add this as an issue. Or raise a pull-request with the required implementation.

Closing because this PR is not valid.

Thanks,
Jonatan

**Comment by RobertRostohar** [comment]
Adding it just to the documentation is not enough. Missing is also the implementation with portable functions.

When would such error indication be useful?

Also keep in mind that debuggers have typically limited number of LEDs.

**Pull request closed without merging**
