### PR TITLE
Fixed macro  error

### PR DESCRIPTION
**Pull request by DavidLin1577**
ARM_SAI_ERROR_FRAME_LENGHT -> ARM_SAI_ERROR_FRAME_LENGTH

### CODE REVIEW

**Comment by JonatanAntoni** [comment]
Hi @DavidLin1577,

thanks for pointing out this typo.

Unfortunately correcting the type is a breaking change to this API. 
I am not sure if we can do this that easily. Perhaps we need to keep the misspelled macro for backward compatibility reasons. I need to check with the team.

Cheers,
Jonatan

**Comment by ilg-ul** [comment]
You can define both, with the incorrect one marked as deprecated.

**Comment by DavidLin1577** [comment]
> You can define both, with the incorrect one marked as deprecated.

@Jonatan Antoni Thanks for your suggestion and countermeasure. I meet something likes this in my work，"define both" is a good idea and new idea to me，thanks again.

**Comment by JonatanAntoni** [comment]
Yep, using `@deprecated` a viable approach. @DavidLin1577 do you plan to update your PR, accordingly? I'd like to ask you to squash your PR into a single commit, please.

**Comment by DavidLin1577** [comment]
> Yep, using `@deprecated` a viable approach. @DavidLin1577 do you plan to update your PR, accordingly? I'd like to ask you to squash your PR into a single commit, please.

@JonatanAntoni My pleasure, I'm glad to do this better, I will squash my PR into a single commit.

**Comment by JonatanAntoni** [comment]
@DavidLin1577, you need to remove that merge commit and rebase/squash all your commits onto master in order to let me merge your changes properly.

**Comment by DavidLin1577** [comment]
> @DavidLin1577, you need to remove that merge commit and rebase/squash all your commits onto master in order to let me merge your changes properly.

@JonatanAntoni thank you for your advise. I got it, but I meet some troubles on this pr when I try serveral times to rebase/squash my commits , I had to fork a new one, and new PR#849. And I will close this pr when #849 finish, thanks.

**Pull request closed without merging**
