### PR TITLE
Fix multiple typedefs for float32_t when using MVEF

### PR DESCRIPTION
**Pull request by jprofeta-rea**
Guards against multiple typedefs for float32_t. 

When the MVEF feature is set, float32 types are defined in "arm_mve.h". This causes a duplicate definition for `float32_t` in "arm_math_types.h" after the inclusion of "arm_mve.h".

### CODE REVIEW

**Comment by grasci-arm** [comment]
Can one of the admins verify this patch?

**Comment by JonatanAntoni** [comment]
Thanks for raising this. The PR seems unclean while containing 50 commits.

@jprofeta-rea, may I ask you to rebase your commit to latest head of develop branch, please? The PR should contain only your single commit.

Cheers,
Jonatan

**Comment by christophe0606** [comment]
@jprofeta-rea Which version are you using ?
It is already corrected in the develop branch of CMSIS-DSP.

I can see this in arm_math_types.h

```
#if !defined(__ICCARM__) || !(__ARM_FEATURE_MVE & 2)
  typedef float float32_t;
#endif
```

The definition of ARM_MATH_MVEF is a consequence of __ARM_FEATURE_MVE & 2 so it is covered by above test.

**Comment by jprofeta-rea** [comment]
@christophe0606 We are using tag 5.8.0. 
I must have missed the fix on develop. I will go ahead and close this PR. Sorry for the inconvenience.
Thanks for the help.

**Pull request closed without merging**
