### PR TITLE
Add stdint.h to arm_nn_types.h

### PR DESCRIPTION
**Pull request by njeffrie**
Ensure int32_t and other stdint types are recognized.

Fixes https://github.com/ARM-software/CMSIS_5/issues/1009

### CODE REVIEW

**Review by advaitjain — APPROVED** [review]

**Comment by advaitjain** [comment]
@freddan80 @jenselofsson let us know what you think.

**Comment by felix-johnny** [comment]
@njeffrie Thanks for the PR and the changes look good. Could  you squash the changes and it make it as a single commit though?

**Comment by felix-johnny** [comment]
@njeffrie @advaitjain .. I have a PR https://github.com/ARM-software/CMSIS_5/pull/1014 up for cleanup of the include files and it includes this change as well. So, you can skip the change I asked for. I'll let you know when that is in..

**Comment by advaitjain** [comment]
Thanks!

**Comment by felix-johnny** [comment]
I'll close this PR as the changes are in now.

**Pull request closed without merging**
