### PR TITLE
Suggestion to add exact sum functions in BasicMathFunctions folder 

### PR DESCRIPTION
**Pull request by Silfurion**
Hello,
In some of our projects, we would like to accelerate the sum of vector elements. At the moment CMSIS doesn't offer a simple sum function. The closest method was the mean method that unfortunately doesn't offer an exact result if we want to multiply its result by the size of the array to get back the sum of the vector.

With this pull request we would like to suggest the addition of a new sum function that would allow to benefit from the already implemented and accelerated mean function, but without the final division to obtain a more accurate sum result.

We added these function in the BasicMathFunctions folder available for q7 , q15 , q31 , float16 , float32 and float64.

Thanks again

### CODE REVIEW

**Comment by grasci-arm** [comment]
Can one of the admins verify this patch?

**Comment by christophe0606** [comment]
@Silfurion I'll need to write and add some tests before I can merge this PR.
Also, I'll rename the function to accumulate if you don't mind.

**Comment by grasci-arm** [comment]
Can one of the admins verify this patch?

**Comment by christophe0606** [comment]
There were some pending questions in this PR.

Accumulation functions are now tracked in this new github issues on the new CMSIS-DSP repository : https://github.com/ARM-software/CMSIS-DSP/issues/12

**Pull request closed without merging**
