### PR TITLE
fix word typo

### PR DESCRIPTION
**Pull request by Guguant**
I'd modify mispelling words to its correct words.

### CODE REVIEW

**Comment by christophe0606** [comment]
This DSP test suite is deprecated and is no more used.

**Comment by Guguant** [comment]
Thanks for your reply. I have designed a spelling typo check program ([run_spelling_typo_check.sh](https://github.com/Guguant/enjoy-code/blob/master/spelling_typo_check/run_spelling_typo_check.sh)) to help to find spelling typo. The typo datasets are from the [linux spelling.txt](https://github.com/torvalds/linux/blob/master/scripts/spelling.txt).

```bash
#!/bin/bash
# run_spelling_typo_check.sh
# test datasets:
#   https://github.com/torvalds/linux/blob/master/scripts/spelling.txt

input=spelling.txt
output=result.txt

if [ -f "$output" ]; then
	> $output
else
	touch $output
fi

line_sum=`awk 'END {print NR}' $input`
index=1
cat $input | while read line
do
	echo "[$index/$line_sum] : $line"

	echo $line [$index/$line_sum] >> $output
	echo "====================" >> $output

	keyword=${line%%|*}
	grep -rsnwi $keyword --exclude $input >> $output
	echo >> $output

	((index++))
done
```

**Comment by christophe0606** [comment]
Thanks. The script is a nice idea.

This pull request is now impacting lot of files outside of DSP.

So I am adding a few other people for review too:
@JonatanAntoni for RTX examples.
@felix-johnny for NN

**Comment by felix-johnny** [comment]
Thanks for the PR! Looks ok for NN.

**Comment by JonatanAntoni** [comment]
Can one of the admins verify this patch?

**Pull request merged**
