### PR TITLE
[CMSIS Core] Set PDEPU low-power state to ON, Clock OFF to favor FP/M…

### PR DESCRIPTION
**Pull request by FabKlein**
[CMSIS Core] Set PDEPU low-power state to ON, Clock OFF to favor FP/MVE performance by default

### CODE REVIEW

**Comment by JonatanAntoni** [comment]
Can one of the admins verify this patch?

**Comment by JonatanAntoni** [comment]
ok to test

**Review by GuentherMartin — COMMENTED** [review]
Please
- Increase version
- set new date
- add an empty line at the end of the file

Code looks OK.

**Review by GuentherMartin — CHANGES_REQUESTED** [review]
Please
- increase version.
- set new date.
- add empty line at end of the file.

Code change looks fine.

**Comment by JonatanAntoni** [comment]
We lack Cortex-M55 configuration for Core Validation tests. Hence the code is not executed on CI, yet.

**Review by GuentherMartin — APPROVED** [review]
Looks fine to me.

**Pull request merged**
