### PR TITLE
Call SystemInit in the very beginning of Reset_Handler

### PR DESCRIPTION
**Pull request by alfedotov**
Related issue #405

### CODE REVIEW

**Comment by ilg-ul** [comment]
Could you also update the documentation to state that calling `SystemCoreClockUpdate()` is mandatory after the .bss section is cleared?

**Comment by alfedotov** [comment]
> 
> 
> Could you also update the documentation to state that calling `SystemCoreClockUpdate()` is mandatory after the .bss section is cleared?
That's interesting thing because .bss can be cleared by library code (newlib for instance), not only cmsis startup code.

**Comment by alfedotov** [comment]
> The ideal solution, that I used in my projects, is to have two system initialisation routines, one called as early as possible (to initialise PLL & external RAM, for example; it can be called `SystemEarlyInit()`), and the second called after the .data & .bss sections are initialised (for all other things, including clock variable initialisation; it can be the current `SystemInit()`), but before the C++ static constructors are executed.

This would be nice solution I agree.
I'm thinking to refactor newlib startup code (at the moment it is a complete hell of ifdef/else vs rdimon/bare-config blocks...) and probably we could tie them more elegantly.

**Comment by ilg-ul** [comment]
> refactor newlib startup code

I don't think that it is reasonable to expect newlib to provide the startup code for CMSIS applications, newlib is a generic library, it may or may not be used by an application.

Not to mention that other toolchains may have different startup requirements.

The startup code must match the linker script and the memory allocator, and, from my experience, the only reasonable place where you can control all three is in the application.

**Comment by JonatanAntoni** [comment]
Hi all,

please bear in mind that current convention is that `SystemInit()` is exactly intended to what @ilg-ul  wants to use it, e.g. early stage external memory configuration. It should run before any library initialization which might otherwise access non-configured external memory. Actually it does exactly this for all compilers other than GCC. Hence I think we should definitively fix it this way.

Having a second hook somewhere in between is another story, e.g. after `.bss` init but before C++ static constructors. I am not an expert on that field. Currently CMSIS recommendation is to call `SystemCoreClockUpdate()` right at the beginning of `main()`. If you think that's too late please feel free to suggest enhancements you see valuable. Don't limit to GCC but take other compilers and libraries into account as well. At which point do you want to see an additional standardized CMSIS hook? How to actually inject it into Arm Compiler, IAR *and* GCC startup?

Thanks for all your contributions.

Cheers,
Jonatan

**Comment by ilg-ul** [comment]
> `SystemCoreClockUpdate()` right at the beginning of `main()`

this might be ok for C, but it is too late for C++.

for GCC, the right place for a second set of system inits is in the startup code, which must be placed in the application, not in the system libraries.

for other unfortunate toolchains... I don't know, but I guess it must be possible to disable the default startup code (same as `-nostartfiles` does for GCC), and allow the startup to be in the application, and be customised as needed.

**Comment by ilg-ul** [comment]
anyway, if I understood it right, the changes apply to the sample files.

vendors will continue to publish their own startup files, where we have no control where `SystemInit()` is placed.

**Comment by ilg-ul** [comment]
> Well I like that approach with SystemEarlyInit() and it perfectly fits with thing I want to get eventually.

for a more elaborate startup, you can take a look at:

https://github.com/micro-os-plus/startup-xpack/blob/xpack/src/startup.cpp

it is intended to be portable, I already used it in some RISC-V projects and I plan to use it for Cortex-M in the next release of µOS++.

**Comment by JonatanAntoni** [comment]
@alfedotov, no we can't. `SystemInit()` is currently defined to be called at early stage. It is exactly implemented this way for other compilers than GCC. So switching between compilers would lead to different behavior which is not the intention of CMSIS.

@ilg-ul, that's the bad part of it. The startup code discussed here is only a template for the templates shipped by silicon vendors as part of their device family packs. Finally the startup code is under full control of the application, intended to be adopted to users needs. That's why fixing it here is not urgent I think.

**Comment by ilg-ul** [comment]
> fixing it here is not urgent I think.

right, it is not urgent, but I think that as template, which apparently does no harm to existing applications, it should probably show the call to `SystemInit()` as early as possible.

and I also think you should really rework the documentation and explain at large why `SystemInit()` should be called early and the need to call `SystemCoreClockUpdate()` later, mandatory right before the static constructors for C++.

**Pull request merged**
