### PR TITLE
Address unsupported nested external declaration #617

### PR DESCRIPTION
**Pull request by ya-mouse**
This should address an issue #617 for Clang compilers.

### CODE REVIEW

**Comment by grasci-arm** [comment]
Can one of the admins verify this patch?

**Comment by ya-mouse** [comment]
This change is mutually exclusive with #1597

**Comment by JonatanAntoni** [comment]
Hi @ya-mouse,

Thanks for raising this. I tend to prefer your second solution in order not to duplicate all the code. GCC and Clang seem to use the same code so we should not duplicate the code.

Cheers,
Jonatan

**Comment by ya-mouse** [comment]
Ok, proceeding with another PR then.

**Pull request closed without merging**
