### PR TITLE
Device: SC300: Fix wrong SC300 core header file inclusion

### PR DESCRIPTION
**Pull request by suren99**
core_sc300.h should be included instead of core_SC300.h

### CODE REVIEW

**Comment by JonatanAntoni** [comment]
Hi @suren99,

thanks for pointing this out.
We need to clean up some additional files along side:
- ARMSC300.h needs update to file header (increment patch version and set change date)
- ARM.CMSIS.pdsc needs to be updated on Startup components for SC300. Both variant's Cversion needs to be incremented on patch.

Would you be so kind and add these changes to your PR, please?

Thanks,
Jonatan

**Comment by JonatanAntoni** [comment]
Additional note: Same issue is in ARMSC000. Would you fix this in a same way as well?

**Comment by suren99** [comment]
Hi @JonatanAntoni 
Yes i will post the requested changes as well. 

> ARM.CMSIS.pdsc needs to be updated on Startup components for SC300. Both variant's Cversion needs to be incremented on patch.

```diff
- <component` Cclass="Device" Cgroup="Startup" Cvariant="C Startup" Cversion="2.0.2" condition="ARMSC300 CMSIS"> 
+ <component Cclass="Device" Cgroup="Startup" Cvariant="C Startup" Cversion="2.0.3" condition="ARMSC300 CMSIS">
 
- <component Cclass="Device" Cgroup="Startup"                      Cversion="1.2.2" condition="ARMSC300 CMSIS">
+ <component Cclass="Device" Cgroup="Startup"                      Cversion="1.2.3" condition="ARMSC300 CMSIS">
```
 Are the above changes correct ?. Are there any other fields that needs to be changed ?. Please let me know if any changes are needed.

Regards,
Surendran.

**Comment by suren99** [comment]
Hi @JonatanAntoni , @GuentherMartin,
Gentle remainder regarding the above comment, Can i proceed with the mentioned changes?

**Comment by JonatanAntoni** [comment]
Sorry, @suren99,
I have been off due to xmas holidays.

Yes, the changes to the pdsc file look good to me. Please update the file header version and date of touched source/header files as well. 

Many thanks for your contribution,
Jonatan

**Comment by JonatanAntoni** [comment]
Looks perfect, thanks!

**Comment by suren99** [comment]
Hi @JonatanAntoni, @GuentherMartin,
Can you review the changes so that we can proceed further?

Thanks,
Surendran

**Pull request merged**
