### PR TITLE
CMSIS-Core(A): Changed __L1C_CleanInvalidateCache function for IAR.

### PR DESCRIPTION
**Pull request by TomoYamanaka**
I changed function by basing on cmsis_gcc.h because the build error(assembly syntax error) will occurs.

### CODE REVIEW

**Comment by bulislaw** [comment]
@JonatanAntoni please review

**Comment by JonatanAntoni** [comment]
Hi @bulislaw,

I already commented this part of the code: It seems not to be specific to IAR so why is it placed in cmsis_iccarm.h? Can we refactor the cache handling to become compiler agnostic?

Cheers,
Jonatan

**Comment by bulislaw** [comment]
@TomoYamanaka ping

**Comment by TomoYamanaka** [comment]
I developed the codes that refactor the cache handling as compiler agnostic in my temporary branch.
https://github.com/TomoYamanaka/CMSIS_5/tree/feature_refactor_cache_handling
I am now focusing on Mbed, compile and test for Cortex-A were successfully by using ARMCC(ver5), GCC(ver6.2) and IAR(ver8.20.1).

Could you review this changes? If there is no problem with the contents, I will give this contents to you as another PR, and close this PR.
Or please let me know if you prefer another review way.

**Comment by JonatanAntoni** [comment]
Hi @TomoYamanaka,

I think the changes are pretty much what we should go for. 

We should not remove `__L1C_CleanInvalidateCache` completeley but keep a stub for compatibility reasons. The stub can be flagged as deprecated and should not be used, i.e. with `__attribute__((deprecated))`.

Another issue I came across while testing the routine is the usage of `L1C_CleanInvalidateCache(0)`. The call stack might get corrupted if this function is not really inlined, e.g. due to low optimization. The values pushed to the stack are by chance not written back before we invalidate the cache content. Thus garbage is restored on function return.

In order to get at least an educated guess whether the implementation does the job we should enhance [CoreValidation](https://github.com/ARM-software/CMSIS_5/tree/develop/CMSIS/CoreValidation) tests. Do you have an idea how we could implement some sort of self-test routine for cache maintenance?

Thanks,
Jonatan

**Comment by JonatanAntoni** [comment]
Hi @TomoYamanaka,

I added this stuff with commit 17b53ef. May I ask you to give it a review, please?

I created some [CoreValidation tests](https://github.com/ARM-software/CMSIS_5/blob/develop/CMSIS/CoreValidation/Source/CV_L1Cache.c) as well. Unfortunately I face some test failures on various configurations, i.e. using IAR and on Cortex-A7. We need to fix these, soon.

Cheers,
Jonatan

**Comment by TomoYamanaka** [comment]
Hi @JonatanAntoni 

> I added this stuff with commit 17b53ef. May I ask you to give it a review, please?

I will review the changes of part of `CMSIS/Core_A/Include/` in commit 17b53ef.
Please give me a little more time.

But sorry, since I can not review the part of `CMSIS/CoreValidation/`, could you please assign other members?

**Comment by TomoYamanaka** [comment]
I reviewed the changes of part of CMSIS/Core_A/Include/ in commit 17b53ef, but I guess that there is a problem in only GCC.
I am now focusing on Mbed, the build error will occur in GCC toolchain only. 
The spot of build error is [here](https://github.com/ARM-software/CMSIS_5/commit/17b53ef2a297ef73d0fb0d720cf2a3458d6127e2#diff-6ebf31aa0077600595814f0e3a7bbaa6R1013), error message is `expected unqualified-id before numeric constant`.
It seems that GCC compiler work as a reserved word of  `__DEPRECATED = 1`.
Reference is [here](\GNU Tools ARM Embedded\6 2017-q2-update\share\doc\gcc-arm-none-eabi\html\cpp\Common-Predefined-Macros.html).
```
__DEPRECATED
This macro is defined, with value 1, when compiling a C++ source file with warnings about deprecated constructs enabled. These warnings are enabled by default, but can be disabled with -Wno-deprecated. 
```
<br>
As a test, when I inserted the below code into the 58th line of cmsis_gcc.h, the build was successful.

`#undef   __DEPRECATED`

**Comment by JonatanAntoni** [comment]
Thx @TomoYamanaka,

We need to rename `__DEPRECATED` to something else in order to prevent that name clash.
What do you think about replacing it with `CMSIS_DEPRECATED`?

Cheers,
Jonatan

**Comment by TomoYamanaka** [comment]
Hi @JonatanAntoni 
Thank you for your comments. 
Your suggestion looks good to me.

**Comment by TomoYamanaka** [comment]
@JonatanAntoni 
Thank you for the update.
Since my PR was replaced to the below commits as a permanent fix, I close this PR.
- https://github.com/ARM-software/CMSIS_5/commit/17b53ef2a297ef73d0fb0d720cf2a3458d6127e2
- https://github.com/ARM-software/CMSIS_5/commit/d43938fac6e0fa1b5682c2ca5704277b6dc34963

**Pull request closed without merging**
