### PR TITLE
Const-correctness of CMSIS-DSP library

### PR DESCRIPTION
**Pull request by torfinnberset**
This is an updated PR to #531, which was reverted in #535. 

This fixes compilation issues with the reference DSP library, and some issues regarding constness reported by @GuentherMartin

### CODE REVIEW

**Comment by torfinnberset** [comment]
The last commit re-applied the `const`ness that was reverted in #535. Please test this and see if the reference implementation passes before merging

**Comment by torfinnberset** [comment]
@JonatanAntoni is there still interest in this PR? Just want to check before I spend the time resolving the 1k merge conflicts 😢

**Comment by JonatanAntoni** [comment]
Hi @torfinnberset,

I would say yes, basically. Unfortunately we don't have free capacities in the team to address this right now. Perhaps you want to leave it as is for the time being. Would be great if we can pick it up again, later.

Thank you very much,
Jonatan

**Comment by torfinnberset** [comment]
@JonatanAntoni ok thanks for getting back to me. I will leave it as is now, and please just ping me when there's time to review and test it. Then I'll merge the HEAD at that time and fix any conflicts.

**Comment by JonatanAntoni** [comment]
Can one of the admins verify this patch?

**Comment by christophe0606** [comment]
I close it.

Too many changes in the CMSIS-DSP since this pull request was made 2 years ago.

And we have improved on the const correctness ...

**Pull request closed without merging**
