### PR TITLE
NN: Change syntax of immediate values in inline assembler

### PR DESCRIPTION
**Pull request by mortior**
The IAR Arm assembler requires the immediate values to be prefixed by a
hash character as described in the architecture reference manual. This
syntax is supported by GCC and Arm compiler 6 as well.

### CODE REVIEW

**Comment by grasci-arm** [comment]
Can one of the admins verify this patch?

**Comment by mansnils** [comment]
@mortior Thank you for the PR! Can I ask you to update date and revision (patch version) in each of the files, and also year to 2022 in the c-files?

**Comment by mansnils** [comment]
@mortior Thank you for the PR! Can I ask you to update date and revision (patch version) in each of the files, and also year to 2022 in the c-files?

**Comment by mortior** [comment]
@mansnils What patch version should I use?

**Comment by mansnils** [comment]
@mortior Please increment the third digit, i.e. Z in X.Y.Z. Thanks!

**Review by mansnils — APPROVED** [review]

**Pull request merged**
