### PR TITLE
DSP: Add IAR tool chain

### PR DESCRIPTION
**Pull request by TTornblom**
Previously known as PR #1337

Signed-off-by: TTornblom <thomas.tornblom@iar.com>

### CODE REVIEW

**Comment by grasci-arm** [comment]
Can one of the admins verify this patch?

**Comment by christophe0606** [comment]
Does it mean it needs to be reviewed again and my latest comments were lost ? Or they have already been taken into account in this new PR ?

**Comment by TTornblom** [comment]
@christophe0606 
Were there other comments than what can be seen in #1337?
As far as I know there were no outstanding issues in #1337.

**Comment by christophe0606** [comment]
@TTornblom It is the same comments.

But from those comments and the code I have question : was it tested on a fast model ? Did you build the CMSIS-DSP test framework with IAR tool chain and you was able to run it on a fast model ?

From the comments I am expecting some issues that's why I had not merged the PR. so far.

**Comment by TTornblom** [comment]
We have sucessfully built and run the examples on our M55 simulator using the FVP platform. We have not attempted to run the test suites.

**Comment by christophe0606** [comment]
@TTornblom It is not a problem if there is no support for IAR toolchain in the test suite. The test suite does not have to support all compilers since it is mainly used internally to validate the algorithms.

So should I close this PR ? It will require much more work if you really want to support the test suite.

**Comment by TTornblom** [comment]
I would like to have this PR merged, not closed without action.

It adds DSP support for the M55 with IAR. Without it compilation fails and with it the examples all builds and runs on the IAR M55 simulator, which also successfully runs the examples built with GNUARM, so it is fairly accurate.

**Comment by christophe0606** [comment]
@TTornblom Ok. Since it is also modifying a few files which are not only for IAR, I'll have to re-check this part and then I'll merge it.

**Comment by christophe0606** [comment]
@TTornblom Can you just answer the comments related to f16 ?
Because I have had some github issue opened related to f16 and IAR.

**Comment by TTornblom** [comment]
@christophe0606 I think the f16 issues were solved by you previously, so this patch is just for allowing the examples to be built and run with the IAR toolchain.

**Pull request merged**
