### PR TITLE
Master

### PR DESCRIPTION
**Pull request by julienoklmoklm**
Bonjour,

SVP j''aurais besoin du pilote wifi ARM.
Merci

### CODE REVIEW

**Comment by grasci-arm** [comment]
Can one of the admins verify this patch?

**Comment by julienoklmoklm** [comment]
Oui

Envoyé de mon iPhone

**Comment by julienoklmoklm** [comment]
I am on Windows 11 in VM on a MacBook Pro

Envoyé de mon iPhone

**Comment by JonatanAntoni** [comment]
This doesn't add serious changes. If you intended to contribute changes be sure to follow the GitHub pull-request workflow. And consider commenting in english, please.

**Pull request closed without merging**
