### PR TITLE
Fix return value for osThreadFlagsWait function

### PR DESCRIPTION
**Pull request by bulislaw**
Documentation specifies that osThreadFlagsWait returns flags before
clearing.

http://arm-software.github.io/CMSIS_5/RTOS2/html/group__CMSIS__RTOS__ThreadFlagsMgmt.html#gac11542ad6300b600f872fc96e340ec2b

### CODE REVIEW

**Comment by bulislaw** [comment]
After some discussions we agreed that current implementation is correct, but the documentation is a bit misleading (as there can be some side effects changing status while the function executes). Closing.

**Comment by JonatanAntoni** [comment]
I slightly enhanced the documentation with an usage example to explain the return values.
@bulislaw please review commit 67a4147 and close this issue again if no more questions to be discussed.

**Comment by bulislaw** [comment]
Looks good, thanks!

**Comment by JonatanAntoni** [comment]
Finally closing.

**Pull request closed without merging**
