### PR TITLE
SVD: fix regex of bitRangeType

### PR DESCRIPTION
**Pull request by duskmoon314**
Fix conflict between the comment and the regex

### CODE REVIEW

**Comment by jkrech** [comment]
Given the fact that today SVDConv is limited to a maximum size of a register to 32-bit, the range value should be 0 to 31, despite the comment reading 69 which I cannot make sense of right now. Am I missing something?

**Comment by duskmoon314** [comment]
> despite the comment reading 69 which I cannot make sense of right now

I think this might be 0-63 which means a 64-bit register. And maybe the first writer thinks it is easy to build up a regex for 69. (I cannot find previous commits on this line in the repo)

I am trying to build up an SVD file of a RISC-V MCU and it has a peripheral with three 64-bit registers. So I see the error of `bitRange`, finding this line and the comment, then open this PR.

**Comment by grasci-arm** [comment]
Can one of the admins verify this patch?

**Comment by JonatanAntoni** [comment]
Please, could you raise this PR to the new location of SVD spec?
Find the discussed spec at https://github.com/Open-CMSIS-Pack/svd-spec/blob/12dc76458ea68e9c1a7b81689207216c1fefa053/schema/CMSIS-SVD.xsd#L256

**Comment by duskmoon314** [comment]
> Please, could you raise this PR to the new location of SVD spec? Find the discussed spec at [Open-CMSIS-Pack/svd-spec@`12dc764`/schema/CMSIS-SVD.xsd#L256](https://github.com/Open-CMSIS-Pack/svd-spec/blob/12dc76458ea68e9c1a7b81689207216c1fefa053/schema/CMSIS-SVD.xsd#L256)

Sure!

**Pull request closed without merging**
