### PR TITLE
CMSIS-Core(M): Fixed incorrect EXC_RETURN_SPSEL definition in ARMv8-M

### PR DESCRIPTION
**Pull request by alexkoeberl**
SPSEL is bit[2] with resulting mask value of 4. Current head selects bit [1], which  is reserved to zero.
Bug introduced with issue #340.

Relevant sections from ARMv8-M Architecture Reference Manual:
image

image

### CODE REVIEW

**Comment by JonatanAntoni** [comment]
Hi @alexkoeberl,

Thanks for pointing this out.

Cheers,
Jonatan

**Comment by JonatanAntoni** [comment]
Hi @alexkoeberl,

may I ask you to raise this PR against the develop branch, please?
And could you please double check if this fix needs to be applied to the new `core_cm35p.h` as well?

Thanks for your contribution,
Jonatan

**Comment by alexkoeberl** [comment]
Hello @JonatanAntoni ,

Is the merge ok as I did it, or should we scrap this PR and create a new one with clean commits?

**Comment by JonatanAntoni** [comment]
Hi @alexkoeberl,

Unfortunately the merge causes weird conflicts. Its always better to use rebase when updating a PR instead of merge. You should be able to reset your branch `fix_exc_return_spsel` to the latest develop and cherry-pick your actual commits back on top of it.

Cheers,
Jonatan

**Comment by alexkoeberl** [comment]
Hi @JonatanAntoni ,

I cleaned up the branch, should be ready for merge now!

BR,
Alex

**Comment by JonatanAntoni** [comment]
Thanks, looks good.

**Pull request closed without merging**
