### PR TITLE
CMSIS-NN: arm_relu_q15: improve code readability

### PR DESCRIPTION
**Pull request by adnan-ashraf**
Improved code readability by removing a redundant line

### CODE REVIEW

**Comment by adnan-ashraf** [comment]
Can someone please review this small improvement? @JonatanAntoni

**Comment by felix-johnny** [comment]
@adnan-ashraf  Thanks for the contribution. I don't think this change causes any change to the generated code. I am referring to disassembled code generated with and without the change. 
 could you explain what you mean by efficiency improvement and how you measured it?

**Comment by adnan-ashraf** [comment]
@felix-johnny Thank you for pointing out, I neither checked the disassembled code nor measured the efficiency. I just wanted to report that redundant line. Let me change the pull request details.

**Comment by felix-johnny** [comment]
@adnan-ashraf I think it is more clear if a dereferenced pointer is incremented. 

With that in mind, I will close this ticket. But, thanks for your time and please do not hesitate to create PR's on any other improvements that you come across.

**Pull request closed without merging**
