### PR TITLE
Add some f64 DSP functions

### PR DESCRIPTION
**Pull request by jeanbie0**
Hello,

This pull request is related to the issue #1226.

It add some float64 functions (the ones I needed):

- All BasicMathFunctions
- arm_sqrt_f64
- arm_cmplx_mag_f64

Like you explain in the issue, it's mostly the same code with type modification.

Regards

Jean

### CODE REVIEW

**Comment by grasci-arm** [comment]
Can one of the admins verify this patch?

**Comment by christophe0606** [comment]
Hi @jeanbie0,

Thanks for this pull request.

I have looked at the code. 

There are a few remaining issues:
1 - You converted the vector code but we are not targeting any core with f64 vectors in CMSIS-DSP so it will not work. So, you need to remove all of the vector code from those files and keep only the scalar code ;

2 - arm_sqrt_f64 has some issues.
It is using f64 asm not supported on the cores we target.
There are still use of sqrtf and x.yyf constants.

Note that if I merge this pull request it will not be in the coming weeks because I am working on other topics currently. And, I'll also have to write some tests before I can merge those functions.

So, you'll have to be patient. 

But, if you have to wait and I plan on refactoring f16, f32 and f64 code to avoid duplication, can you wait a bit more and use my refactoring with the new f64 functions ? In that case, I would not merge this pull request.

Thanks.

**Comment by jeanbie0** [comment]
Hi @christophe0606 ,

Thank for your review. I only use scalar code so I copy/paste vector code.
I'll wait for your refactoring it'll be easier and more efficient.

**Comment by christophe0606** [comment]
Issue #1226 was closed so I close this pull request too.

More f64 functions are now available and more will be added in the future but we are already covering lots of important functions.

**Pull request closed without merging**
