### PR TITLE
GCC: remove unneeded asm volatiles

### PR DESCRIPTION
**Pull request by kjbracey-arm**
Many assembler intrinsics are pure - they read only the input registers, write only the output registers, and change no PSR flags.

Remove volatile from all such intrinisics to improve potential optimisation.

   REV, REV16, REVSH, RBIT
   QADD8, SHADD8, UQADD8, UHADD8
   QSUB8, SHSUB8, UQSUB8, UHSUB8
   QADD16, SHADD16, UQADD16, UHADD16
   QSUB16, SHSUB16, UQSUB16, UHSUB16
   QASX, SHASX, UQASX, UHASX
   QSAX, SHSAX, UQSAX, UHSAX
   USAD8, USADA8
   UXTB16, UXTAB16, SXTB16, SXTAB16
   SMMLA

Relates to issue #499.

### CODE REVIEW

**Comment by kjbracey-arm** [comment]
Just added a second commit fixing up the odd declaration of REV16 in Core_A version.

**Comment by grubbymits** [comment]
SADD16 writes to the GE bits, whereas QADD16 doesn't read or write to any bits in the APSR.

**Comment by GuentherMartin** [comment]
I see.
Does this mean that 'asm volatile' is necessary if any flags are updated?

**Comment by sparker-arm** [comment]
Yes, it will be used to prevent instructions from being reordered where data dependencies aren't obvious to the compiler. For sadd16, we wouldn't want it to be moved past the sel instruction that reads the GE flags.

**Comment by GuentherMartin** [comment]
So 'asm volatile' is used not because of the flags but because of the possible reorder of instructions.
In other words: 'asm volatile' is used when compiler optimization is not wanted/allowed.

**Comment by GuentherMartin** [comment]
Thank you for the explanation.

**Comment by kjbracey-arm** [comment]
FWIW, you could also force ordering between PSR-setting and PSR-using ops by using "memory" clobbers ("this reads or writes unspecified memory") on all PSR-related things, but that almost certainly inhibits more wanted optimisations than "volatile" - it forces a register spill to memory for whatever data you were manipulating, and really gums up scheduling.

And using "cc" clobbers doesn't work - I tried it. GCC only interprets that as "writes to flags", not "reads from flags", so you can't use it to keep a MRS or SSEL after a SADD8. (The "memory" clobber is special, considering the possibility of reads - all other clobbers are write-only).

**Comment by JonatanAntoni** [comment]
Merged in efa5af1 and 4d8dc46

**Pull request closed without merging**
